"""Add Activity and Staff models

Revision ID: 548dcaa57192
Revises: 7ec86e20aeb1
Create Date: 2025-10-24 14:03:11.011447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548dcaa57192'
down_revision = '7ec86e20aeb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Staff',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Activities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('artist_id', sa.BigInteger(), nullable=False),
    sa.Column('activity_name', sa.Text(), nullable=False),
    sa.Column('activity_type', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['Staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('media_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('media_name')
        batch_op.drop_column('thumbnail')

    op.drop_table('Activities')
    op.drop_table('Staff')
    # ### end Alembic commands ###
