"""Schema check after DB restore

Revision ID: 7ec86e20aeb1
Revises: 896ebeda407a
Create Date: 2025-10-24 11:14:01.336628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ec86e20aeb1'
down_revision = '896ebeda407a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('instagram', 'youtube', 'tiktok', 'twitter'), nullable=False),
    sa.Column('api_name', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('api_secret', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('database_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_name')
    )
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('board_type', sa.Enum('notice', 'announcement', 'general'), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('instagram', 'youtube', 'tiktok', 'twitter'), nullable=False),
    sa.Column('channel_id', sa.String(length=100), nullable=False),
    sa.Column('channel_name', sa.String(length=200), nullable=True),
    sa.Column('channel_url', sa.Text(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id', 'platform', 'channel_id', name='unique_channel')
    )
    op.create_table('channel_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'stat_date', name='unique_channel_date')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('post_url', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('media_type', sa.Enum('image', 'video', 'carousel'), nullable=False),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'post_id', name='unique_post')
    )
    with op.batch_alter_table('Role_Types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('role_name'))

    op.drop_table('Role_Types')
    with op.batch_alter_table('model_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('category_name'))

    op.drop_table('model_categories')
    op.drop_table('Artist_Assets')
    op.drop_table('Recommendation')
    op.drop_table('Albums')
    op.drop_table('ContractInfo')
    op.drop_table('Users')
    op.drop_table('Artist_Schedules')
    op.drop_table('Staff')
    op.drop_table('Agencies')
    op.drop_table('Activities')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=64),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=128),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('last_login')
        batch_op.drop_column('account_id')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('artist_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('published_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('crawled_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('thumbnail',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('media_name',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('unique_news_url'), mysql_length={'url': 255})
        batch_op.drop_constraint(batch_op.f('news_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Artists', ['artist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('news_ibfk_1'), 'Artists', ['artist_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('unique_news_url'), ['url'], unique=True, mysql_length={'url': 255})
        batch_op.alter_column('media_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('thumbnail',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('crawled_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('published_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('artist_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('last_login', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=128),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=64),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('id')

    op.create_table('Activities',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('activity_name', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('activity_type', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('start_time', mysql.DATETIME(), nullable=True),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('location', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('manager_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['Staff.id'], name='Activities_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Agencies',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('founded_date', sa.DATE(), nullable=True),
    sa.Column('location', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Staff',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('position', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('contact_phone', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=20), nullable=True),
    sa.Column('email', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('agency_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['Agencies.id'], name='Staff_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Artist_Schedules',
    sa.Column('artist_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('activity_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['Activities.id'], name=op.f('Artist_Schedules_ibfk_2')),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], name=op.f('Artist_Schedules_ibfk_1')),
    sa.PrimaryKeyConstraint('artist_id', 'activity_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Users',
    sa.Column('uqid', mysql.INTEGER(), autoincrement=True, nullable=False, comment='키값'),
    sa.Column('level', mysql.VARCHAR(length=10), nullable=False, comment='권한'),
    sa.Column('utitle', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('uname', mysql.VARCHAR(length=30), nullable=False, comment='이름'),
    sa.Column('uid', mysql.VARCHAR(length=30), nullable=False, comment='아이디'),
    sa.Column('upass', mysql.VARCHAR(length=300), nullable=False, comment='비밀번호'),
    sa.Column('uemail', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('utax', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('uhead', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('udepart', mysql.INTEGER(), autoincrement=False, nullable=True, comment='부서'),
    sa.Column('uphoto', sa.VARBINARY(length=500), nullable=True, comment='사진'),
    sa.Column('status', mysql.VARCHAR(length=10), server_default=sa.text("'Y'"), nullable=False, comment='상태'),
    sa.Column('regdate', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('hiredate', sa.DATE(), nullable=True),
    sa.Column('last_login', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='zusam.ai 로그인시 업데이트 됨'),
    sa.Column('service_name', mysql.VARCHAR(length=20), nullable=True, comment='이용한  서비스 메뉴(Link)'),
    sa.PrimaryKeyConstraint('uqid', 'uname', 'uid'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('ContractInfo',
    sa.Column('artist_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('fee_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('fee_amount', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('validity_year', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], name=op.f('ContractInfo_ibfk_1')),
    sa.PrimaryKeyConstraint('artist_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Albums',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('release_date', sa.DATE(), nullable=True),
    sa.Column('artist_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], name=op.f('Albums_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Recommendation',
    sa.Column('artist_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('reason_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=100), nullable=True),
    sa.Column('description', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('source', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], name=op.f('Recommendation_ibfk_1')),
    sa.PrimaryKeyConstraint('artist_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Artist_Assets',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('artist_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('asset_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('file_path', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('description', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('upload_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], name=op.f('Artist_Assets_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('model_categories',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('category_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('category_index', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('model_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('category_name'), ['category_name'], unique=True)

    op.create_table('Role_Types',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('role_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Role_Types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('role_name'), ['role_name'], unique=True)

    op.drop_table('posts')
    op.drop_table('channel_stats')
    op.drop_table('channels')
    op.drop_table('boards')
    op.drop_table('database_configs')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
