"""Initial migration.

Revision ID: 896ebeda407a
Revises: 
Create Date: 2025-10-24 02:29:38.708316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '896ebeda407a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Staff')
    op.drop_table('Artists')
    op.drop_table('CareerHistory')
    op.drop_table('Songs')
    op.drop_table('Artist_Schedules')
    op.drop_table('Boards')
    op.drop_table('Artist_Awards')
    op.drop_table('Agencies')
    with op.batch_alter_table('model_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('category_name'))

    op.drop_table('model_categories')
    op.drop_table('ContractInfo')
    op.drop_table('Users')
    op.drop_table('Albums')
    with op.batch_alter_table('Role_Types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('role_name'))

    op.drop_table('Role_Types')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('username'))

    op.drop_table('accounts')
    op.drop_table('Activities')
    op.drop_table('Artist_Assets')
    op.drop_table('Recommendation')
    op.drop_table('Artist_Roles')
    op.drop_table('Artist_Managers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artist_Managers',
    sa.Column('artist_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('staff_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], name=op.f('Artist_Managers_ibfk_1')),
    sa.ForeignKeyConstraint(['staff_id'], ['Staff.id'], name=op.f('Artist_Managers_ibfk_2')),
    sa.PrimaryKeyConstraint('artist_id', 'staff_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Artist_Roles',
    sa.Column('artist_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('role_type_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], name=op.f('Artist_Roles_ibfk_1')),
    sa.ForeignKeyConstraint(['role_type_id'], ['Role_Types.id'], name=op.f('Artist_Roles_ibfk_2')),
    sa.PrimaryKeyConstraint('artist_id', 'role_type_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Recommendation',
    sa.Column('artist_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('reason_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=100), nullable=True),
    sa.Column('description', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('source', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], name=op.f('Recommendation_ibfk_1')),
    sa.PrimaryKeyConstraint('artist_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Artist_Assets',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('artist_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('asset_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('file_path', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('description', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('upload_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], name=op.f('Artist_Assets_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Activities',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('activity_name', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('activity_type', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('start_time', mysql.DATETIME(), nullable=True),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('location', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('manager_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['Staff.id'], name='Activities_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('accounts',
    sa.Column('account_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=64), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=128), nullable=False),
    sa.Column('role', mysql.ENUM('admin', 'user'), server_default=sa.text("'user'"), nullable=True),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('account_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('Role_Types',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('role_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Role_Types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('role_name'), ['role_name'], unique=True)

    op.create_table('Albums',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('release_date', sa.DATE(), nullable=True),
    sa.Column('artist_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], name='Albums_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Users',
    sa.Column('uqid', mysql.INTEGER(), autoincrement=True, nullable=False, comment='키값'),
    sa.Column('level', mysql.VARCHAR(length=10), nullable=False, comment='권한'),
    sa.Column('utitle', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('uname', mysql.VARCHAR(length=30), nullable=False, comment='이름'),
    sa.Column('uid', mysql.VARCHAR(length=30), nullable=False, comment='아이디'),
    sa.Column('upass', mysql.VARCHAR(length=300), nullable=False, comment='비밀번호'),
    sa.Column('uemail', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('utax', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('uhead', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('udepart', mysql.INTEGER(), autoincrement=False, nullable=True, comment='부서'),
    sa.Column('uphoto', sa.VARBINARY(length=500), nullable=True, comment='사진'),
    sa.Column('status', mysql.VARCHAR(length=10), server_default=sa.text("'Y'"), nullable=False, comment='상태'),
    sa.Column('regdate', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('hiredate', sa.DATE(), nullable=True),
    sa.Column('last_login', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='zusam.ai 로그인시 업데이트 됨'),
    sa.Column('service_name', mysql.VARCHAR(length=20), nullable=True, comment='이용한  서비스 메뉴(Link)'),
    sa.PrimaryKeyConstraint('uqid', 'uname', 'uid'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('ContractInfo',
    sa.Column('artist_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('fee_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('fee_amount', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('validity_year', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], name=op.f('ContractInfo_ibfk_1')),
    sa.PrimaryKeyConstraint('artist_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('model_categories',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('category_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('category_index', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('model_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('category_name'), ['category_name'], unique=True)

    op.create_table('Agencies',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('founded_date', sa.DATE(), nullable=True),
    sa.Column('location', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Artist_Awards',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('artist_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('award_name', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('award_year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], name=op.f('Artist_Awards_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Boards',
    sa.Column('board_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=128), nullable=False),
    sa.Column('content', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['Users.uqid'], name=op.f('Boards_ibfk_1')),
    sa.PrimaryKeyConstraint('board_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Artist_Schedules',
    sa.Column('artist_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('activity_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['Activities.id'], name=op.f('Artist_Schedules_ibfk_2')),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], name=op.f('Artist_Schedules_ibfk_1')),
    sa.PrimaryKeyConstraint('artist_id', 'activity_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Songs',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('duration', mysql.TIME(), nullable=True),
    sa.Column('album_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['Albums.id'], name=op.f('Songs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('CareerHistory',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('artist_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('type', mysql.ENUM('드라마', '영화', '방송', '광고', '공연', '기타'), nullable=False),
    sa.Column('year', mysql.YEAR(), nullable=True),
    sa.Column('title', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('memo', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], name=op.f('CareerHistory_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Artists',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.Column('birth_date', sa.DATE(), nullable=False),
    sa.Column('height_cm', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('debut_date', sa.DATE(), nullable=True),
    sa.Column('genre', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=100), nullable=True),
    sa.Column('agency_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('nationality', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=100), nullable=True),
    sa.Column('is_korean', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('gender', mysql.ENUM('WOMAN', 'MEN', 'EXTRA', 'FOREIGN'), nullable=True),
    sa.Column('status', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('category_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('platform', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('social_media_url', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('profile_photo', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Staff',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('position', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('contact_phone', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=20), nullable=True),
    sa.Column('email', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('agency_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['Agencies.id'], name=op.f('Staff_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
